name: pokedex
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  objectbox: ^1.6.2
  objectbox_flutter_libs: any
  flutter_svg: ^1.1.5
  dio: ^4.0.6
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_lints: ^2.0.0

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: src/core/entities

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: TTNorms_Bold
      fonts:
        - asset: assets/fonts/TTNormsPro_Bold.ttf
          
    - family: TTNorms_Medium
      fonts:
        - asset: assets/fonts/TTNormsPro_Medium.ttf
          
    - family: TTNorms_Regular
      fonts:
        - asset: assets/fonts/TTNormsPro_Regular.ttf
          
    - family: TTNormsPro_Light
      fonts:
        - asset: assets/fonts/TTNormsPro_Light.ttf